default: Run20190708

Execute: TranscribeToTextFile.cpp
	CompileRootMacro TranscribeToTextFile.cpp Execute

Run20190708: Execute
	./Execute --Input 20190708/h2files.root --Histogram jersf --Output ZMuMu2018.txt



